### ISSUE TITLE
After 24  hour is creates a new sensor

### ISSUE THREAD

**Issue by Voxxie** [arjenbos/ha-postnl#26]
I've updated to version 2.0. 

I've first deleted the old integration and sensors and reinstalled the addon. 

After 24 hour the integration creates a new sensor:

![Screenshot_2024-11-22-19-07-28-890_io.homeassistant.companion.android.jpg](https://github.com/user-attachments/assets/2de69911-2772-4925-9eff-19050a8758fb)

**Comment by lolie145** [comment]
same here but also creates the new sensors when i reload the integration hub

**Comment by Voxxie** [comment]
If you need anything to help, please let me know.

**Comment by arjenbos** [comment]
Hopefully this will do the trick #27. I created a new beta version (v2.0.1). Could you please install it and see what happens? You may need to remove the old entities (no need to remove the whole integration) due to the bug.

You can remove the entities by clicking on `delete` at the entity settings. You can only delete entities that are unavailable.

**Comment by PieterBoeren** [comment]
I had the same issue, but this beta version seems to fix it :)

**Comment by lolie145** [comment]
beta fixed it!

**Comment by Voxxie** [comment]
Fixed in 2.0.1
